### ISSUE TITLE
Error creating repo

### ISSUE THREAD

**Issue by pavanparthasarathy** [OElesin/querypal#3]
Hi @OElesin I'm getting the below error when I deploy.
"ResourceStatusReason": "There was an issue setting up your repository. Please try again later.({\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest/reference/repos#create-a-repository-webhook\"}) (Service: Amplify; Status Code: 400; Error Code: BadRequestException; Request ID: ebeff70b-d562-4227-a7dd-ec21cda3b1fe; Proxy: null)",

**Comment by dattajoshi** [comment]
I'm facing this issue too..... Is there any update on this??

**Comment by OElesin** [comment]
@dattajoshi and @pavanparthasarathy, 

I'm not sure why you are seeing this error, but I will assume that you need to setup a GitHub token required for a webhook .

Give this a try.

**Comment by pavanparthasarathy** [comment]
@OElesin I have setup the token, it fails post that step.
![image](https://user-images.githubusercontent.com/78717529/107321602-d6855d80-6ac8-11eb-86d6-758b2e51c16b.png)

**Comment by OElesin** [comment]
@pavanparthasarathy, thanks for sharing the screenshot. I looked at it and it appears that the right parameter for the Amplify App name i.e. `QUERYPAL_AMPLIFY_NAME` was not set properly. I made the changes and hopefully this should resolve it.

Please pull the latest changes and try again.

**Comment by pavanparthasarathy** [comment]
@OElesin I'm still getting the same error. Please find the screenshot
![image](https://user-images.githubusercontent.com/78717529/107601851-d2cf1380-6c4d-11eb-896b-045d223f1188.png)

**Comment by tylerdelange** [comment]
I was also really hoping to give this a try, but I am also getting the same error as above, and I do have my GitHub key set...

-----

There was an issue setting up your repository. Please try again later.({"message":"Not Found","documentation_url":"https://docs.github.com/rest/reference/repos#create-a-repository-webhook"}) (Service: Amplify; Status Code: 400; Error Code: BadRequestException; Request ID: bda4d2b8-7d5a-4908-8862-d8b4f699ed42; Proxy: null)

------

**Comment by OElesin** [comment]
@tylerdelange , this is quite strange. It should have been solved. I'll have another look.

**Comment by optus-leo** [comment]
I have the same issue with the others.

**Comment by optus-leo** [comment]
hi @OElesin , do you have any updates on this?

**Comment by OElesin** [comment]
Closing this as issue with deployment has been resolved in the newest updates. Kindly reopen if you still experience this.
